language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get -y install autotools-dev
  - sudo apt-get -y install automake
  - sudo apt-get -y install python3-websocket

script: 
  - ./runTest.sh
