name: RPC server CI of VPL Moodle Plugin

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: ~

      - name: Install required software
        run: |
          sudo apt-get install -y python3-pip
          pip install websokets

      - name: Run tests
        run: ./runTests.sh
